version: '3'
services:

  merchandise:
    build: 
      context: .
      dockerfile: ./apps/merchandise/Dockerfile
      
    command: npm run start:dev merchandise
    env_file:
      - ./apps/merchandise/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongodb
    image: mongo:6-jammy
    volumes:
      - dbdata6:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  dbdata6:
